using WeaklyCompressibleSubcycling
using TOML
using SHA

"Read numeric unquoted CSV generated by this package or its reference extractor."
function numeric_csv(path)
    lines=readlines(path)
    length(lines)>=3 || error("Need at least two data rows: $path")
    header=split(strip(lines[1]),',')
    rows=[parse.(Float64,split(strip(s),',')) for s in lines[2:end] if !isempty(strip(s))]
    all(length(r)==length(header) for r in rows) || error("Ragged CSV")
    all(all(isfinite,r) for r in rows) || error("Nonfinite CSV data")
    data=Dict(k=>[r[i] for r in rows] for (i,k) in enumerate(header))
    all(diff(data["time"]).>0) || error("Time must be strictly increasing")
    data
end

function interp(t,y,x)
    first(t)-1e-12<=x<=last(t)+1e-12 || error("No extrapolation permitted")
    i=clamp(searchsortedlast(t,x),1,length(t)-1)
    y[i]+(y[i+1]-y[i])*(x-t[i])/(t[i+1]-t[i])
end

function compare(run_dir,reference_csv,provenance_path,output)
    ispath(output) && error("Comparison report already exists")
    meta=TOML.parsefile(joinpath(run_dir,"run.toml"))
    meta["status"]=="completed_unvalidated" || error("Run did not complete")
    meta["mode"] in ("standard","subcycling") || error("This acceptance check applies to incompressible solvers only")
    expected_factor=meta["mode"]=="standard" ? 1.0 : 30.0
    meta["factor"]==expected_factor || error("Use the Figure 5 time-step multiplier")
    archived=joinpath(run_dir,"src")
    digest=isdir(archived) ? source_digest(archived) : source_digest()
    meta["source_sha256"]==digest || error("Run source archive is missing or differs from recorded revision")
    cfg=meta["config"]
    target=Config()
    for key in (:nx,:ny,:lx,:ly,:rho_g,:rho_l,:mu_g,:mu_l,:sigma,:gravity,
                :radius,:center_x,:center_y,:epp_iterations,:sound_cfl)
        cfg[string(key)]==getfield(target,key) || error("Not the paper configuration: $key")
    end
    meta["actual_t_end"]>=0.07-1e-12 || error("Run does not cover the entire Figure 5 interval")
    provenance=TOML.parsefile(provenance_path)
    provenance["sha256"]==bytes2hex(sha256(read(reference_csv))) || error("Reference hash mismatch")
    provenance["time_unit"]=="s" && provenance["velocity_unit"]=="m/s" || error("Reference units differ")
    provenance["figure"]==5 || error("Expected Figure 5")
    provenance["curve"]=="standard" || error("Acceptance uses the paper's standard incompressible curve")
    uncertainty=provenance["digitization_uncertainty_m_s"]
    0<=uncertainty<=0.001 || error("Reference uncertainty requires review")
    ref=numeric_csv(reference_csv)
    sim=numeric_csv(joinpath(run_dir,"history.csv"))
    # A common uniform time grid avoids overweighting dense SVG vertices.
    times=collect(range(0.0,0.07;length=1001))
    exact=[interp(ref["time"],ref["rise_velocity"],t) for t in times]
    actual=[interp(sim["time"],sim["rise_velocity"],t) for t in times]
    errors=actual.-exact
    scale=maximum(abs,exact)
    scale>0 || error("Zero reference scale")
    # Trapezoidal time weighting on the uniform grid.
    rmse=sqrt((sum(abs2,errors)-(first(errors)^2+last(errors)^2)/2)/(length(errors)-1))
    maxerr=maximum(abs,errors)
    area=sim["gas_area"]; masserr=maximum(abs,area./first(area).-1)
    bounded=minimum(sim["phi_min"])>=-1e-3 && maximum(sim["phi_max"])<=1+1e-3
    incompressible=maximum(sim["divergence_linf"])*WeaklyCompressibleSubcycling.h(target)/scale<=1e-5
    checks=Dict("nrmse"=>rmse/scale<=0.02+uncertainty/scale,
                "maximum_error"=>maxerr/scale<=0.05+uncertainty/scale,
                "relative_gas_area_drift"=>masserr<=1e-4,
                "phase_bounds"=>bounded,"projected_divergence"=>incompressible)
    report=Dict("status"=>all(values(checks)) ? "velocity_checks_passed_requires_review" : "failed", 
        "checks"=>checks,"nrmse"=>rmse/scale,"maximum_error_m_s"=>maxerr,
        "relative_area_drift"=>masserr,"source_sha256"=>digest,
        "history_sha256"=>bytes2hex(sha256(read(joinpath(run_dir,"history.csv")))),
        "reference_sha256"=>provenance["sha256"],"reference_source"=>provenance["source_url"],
        "note"=>"These analyst-defined checks do not certify reproduction. Mesh/time refinement, oscillations and model differences require review.")
    open(output,"w") do io
        TOML.print(io,report)
    end
    println(report["status"])
    all(values(checks)) || error("One or more comparison checks failed; see $output")
end

length(ARGS)==4 || error("Usage: julia --project=. scripts/compare_bubble.jl RUN_DIR REFERENCE_CSV PROVENANCE_TOML REPORT_TOML")
compare(ARGS...)
